import type { City } from '@/types'

export const CITIES: City[] = [
  {
    id: 'nepal',
    name: 'KATHMANDU',
    region: 'SOUTH ASIA · 尼泊尔',
    lat: 27.70,
    lon: 85.32,
    type: 'current',
    statusText: '最近到访 2026.02',
    coords: '27.700° N · 85.318° E',
    desc: '喜马拉雅山脚下的古老王国，加德满都的街道混合着寺庙香火、摩托车尾气与随处可见的流浪神牛。时间在这里以不同的刻度流动。',
    articles: [],
  },
  {
    id: 'japan',
    name: 'JAPAN',
    region: 'EAST ASIA · 日本',
    lat: 35.68,
    lon: 139.69,
    type: 'lived',
    statusText: '到访 2026.01',
    coords: '35.689° N · 139.692° E',
    desc: '东京是矛盾的城市：极度高效又极度治愈。城市基础设施无可挑剔，便利店是另一种宇宙，但长期居留的成本需要仔细核算。',
    articles: [
      { title: '东京游牧的真实花销', tag: '成本' },
      { title: '下北泽、中目黑与吉祥寺：选哪里落脚', tag: '选区' },
    ],
  },
  {
    id: 'singapore',
    name: 'SINGAPORE',
    region: 'SOUTHEAST ASIA · 新加坡',
    lat: 1.35,
    lon: 103.82,
    type: 'lived',
    statusText: '到访 2025.11',
    coords: '1.352° N · 103.820° E',
    desc: '新加坡是东南亚的高效枢纽，也是离岸账户与企业注册的热门选择。狮城的秩序感与多元文化并存，是数字游民的优质中转站。',
    articles: [
      { title: '新加坡：值得为它多停留几天的理由', tag: '观察' },
    ],
  },
  {
    id: 'thailand',
    name: 'THAILAND',
    region: 'SOUTHEAST ASIA · 泰国',
    lat: 18.79,
    lon: 98.98,
    type: 'lived',
    statusText: '到访 2025.05',
    coords: '18.788° N · 98.985° E',
    desc: '清迈是数字游民的精神故乡。古城、咖啡馆、佛寺与热带丛林在方圆几公里内共存，慢节奏的生活让创作变得格外顺畅。',
    articles: [
      { title: '清迈数字游民生存指南', tag: '攻略' },
      { title: '我最爱的 5 家清迈远程办公咖啡馆', tag: '选址' },
      { title: '清迈租房避坑全记录', tag: '住宿' },
    ],
  },
  {
    id: 'malaysia',
    name: 'MALAYSIA',
    region: 'SOUTHEAST ASIA · 马来西亚',
    lat: 3.14,
    lon: 101.69,
    type: 'lived',
    statusText: '到访 2025.02',
    coords: '3.140° N · 101.687° E',
    desc: '吉隆坡的双子塔下是意想不到的多元——马来人、华人、印度人的日常在同一个街区叠加。物价友好，英语通行，是东南亚最容易融入的城市之一。',
    articles: [
      { title: '吉隆坡旅居一周的生活切片', tag: '生活' },
    ],
  },
  {
    id: 'china',
    name: 'CHINA',
    region: 'EAST ASIA · 中国',
    lat: 39.90,
    lon: 116.40,
    type: 'visited',
    statusText: '2018.07',
    coords: '39.904° N · 116.407° E',
    desc: '故乡或出发地。所有的游荡，都有一个起点。',
    articles: [],
  },
]
